#!/usr/bin/env bash
set -euo pipefail

selected=$(cat ~/.config/tmux/.tmux-cht-languages ~/.config/tmux/.tmux-cht-command | fzf)
if [[ -z "$selected" ]]; then
    exit 0
fi

read -rp "Enter Query: " query

if grep -qs "$selected" ~/.config/tmux/.tmux-cht-languages; then
    query=$(echo "$query" | tr ' ' '+')
    if [[ -n "$query" ]]; then
        tmux neww bash -c "echo 'curl cht.sh/$selected/$query/'; curl -s 'cht.sh/$selected/$query' | less -R"
    else
        tmux neww bash -c "curl -s 'cht.sh/$selected' | less -R"
    fi
else
    if [[ -n "$query" ]]; then
        tmux neww bash -c "curl -s 'cht.sh/$selected~$query' | less -R"
    else
        tmux neww bash -c "curl -s 'cht.sh/$selected' | less -R"
    fi
fi

