#:schema https://github.com/joshmedeski/sesh/raw/main/sesh.schema.json

blacklist = [ "scratch" ]
cache = true

[default_session]
windows = [ "dev" ]

[[session]]
name = "nvimconf"
path = "~/personal/dotfiles/nvim"
windows = [ "dev" ]

[[wildcard]]
pattern = "~/personal/*"
windows = [ "dev" ]

[[wildcard]]
pattern = "~/work/*"
windows = [ "dev" ]

[[window]]
name = "dev" 
startup_script = "~/.config/sesh/scripts/dev_layout.sh"
